apiVersion: v1
kind: Service
metadata:
  name: bling-bling
spec:
  type: NodePort
  selector:
    app: bling-bling
  ports:
    - protocol: TCP
      port: 5000  # Port within the cluster (in dev mode: in minikube)
      targetPort: 5000  # Port within the bling-bling container (connected to Flask that's running on port 5000)
      nodePort: 30036  # Port on the node (in dev mode: in laptop)